tasks:
  - name: Setup Google Cloud SDK
    before: curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-362.0.0-linux-x86_64.tar.gz && tar -xf google-cloud-sdk-362.0.0-linux-x86_64.tar.gz && ./google-cloud-sdk/install.sh && rm -r google-cloud-sdk && rm -r google-cloud-sdk-362.0.0-linux-x86_64.tar.gz
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true